/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI */

#ifndef _Included_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
#define _Included_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DRAW
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DRAW 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WMATE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WMATE 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BMATE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BMATE 2L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_FORBID
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_FORBID 3L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_UNKNOWN
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_UNKNOWN 7L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WHITE_TO_MOVE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WHITE_TO_MOVE 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BLACK_TO_MOVE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BLACK_TO_MOVE 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_NO_PIECE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_NO_PIECE 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_PAWN
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_PAWN 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_KNIGHT
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_KNIGHT 2L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BISHOP
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BISHOP 3L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_ROOK
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_ROOK 4L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_QUEEN
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_QUEEN 5L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_KING
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_KING 6L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_NO_SQUARE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_NO_SQUARE 64L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_NO_CASTLE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_NO_CASTLE 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WSHORT
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WSHORT 8L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WLONG
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WLONG 4L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BSHORT
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BSHORT 2L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BLONG
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BLONG 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_UNCOMPRESSED
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_UNCOMPRESSED 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP1
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP1 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP2
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP2 2L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP3
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP3 3L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP4
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_CP4 4L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_EASY_HITS
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_EASY_HITS 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_HARD_PROB
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_HARD_PROB 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_SOFT_PROB
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_SOFT_PROB 2L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_CACHE_SIZE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_CACHE_SIZE 3L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_EASY_HITS
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_EASY_HITS 4L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_HARD_PROB
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_HARD_PROB 5L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_SOFT_PROB
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_SOFT_PROB 6L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_CACHE_SIZE
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_CACHE_SIZE 7L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_TOTAL_HITS
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_TOTAL_HITS 8L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_MEMORY_HITS
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_MEMORY_HITS 10L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DRIVE_HITS
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DRIVE_HITS 11L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DRIVE_MISSES
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DRIVE_MISSES 12L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BYTES_READ
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_BYTES_READ 13L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_FILES_OPENED
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_FILES_OPENED 14L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_OCCUPANCY
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_WDL_OCCUPANCY 0L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_OCCUPANCY
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_DTM_OCCUPANCY 1L
#undef net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_MEMORY_EFFICIENCY
#define net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_MEMORY_EFFICIENCY 2L
/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    init
 * Signature: (ZILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_init
  (JNIEnv *, jobject, jboolean, jint, jstring);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    restart
 * Signature: (ZILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_restart
  (JNIEnv *, jobject, jboolean, jint, jstring);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    isInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_isInit
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    availability
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_availability
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    indexMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_indexMemory
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_close
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    initCache
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_initCache
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    restartCache
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_restartCache
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    isCacheOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_isCacheOn
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    clearCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_clearCache
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    closeCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_closeCache
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    getStats
 * Signature: ([J[D)V
 */
JNIEXPORT void JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_getStats
  (JNIEnv *, jobject, jlongArray, jdoubleArray);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    resetStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_resetStats
  (JNIEnv *, jobject);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    probe
 * Signature: (III[I[I[C[C)[I
 */
JNIEXPORT jintArray JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_probe
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jcharArray, jcharArray);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    probeSoft
 * Signature: (III[I[I[C[C)[I
 */
JNIEXPORT jintArray JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_probeSoft
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jcharArray, jcharArray);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    probeWDL
 * Signature: (III[I[I[C[C)I
 */
JNIEXPORT jint JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_probeWDL
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jcharArray, jcharArray);

/*
 * Class:     net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI
 * Method:    probeSoftWDL
 * Signature: (III[I[I[C[C)I
 */
JNIEXPORT jint JNICALL Java_net_viktorc_detroid_framework_engine_GaviotaTableBaseJNI_probeSoftWDL
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jcharArray, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
